/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package info;

import dbUtils.db;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 * public@author fabia
 */
class LogInGUI extends javax.swing.JFrame {

    private String userPwd;
    private String userName;

    /**
     * Creates new form LogInGUI
     */
    public LogInGUI() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        userName = "";
        userPwd = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHome = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pnlBread = new javax.swing.JPanel();
        layerdPaneLogIn = new javax.swing.JLayeredPane();
        pnlLogIn = new javax.swing.JPanel();
        lblUserName = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        lblUserPassword = new javax.swing.JLabel();
        pwdUserPassword = new javax.swing.JPasswordField();
        btnLogIn = new javax.swing.JButton();
        pnlFooter = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setSize(new java.awt.Dimension(1024, 768));
        getContentPane().setLayout(new java.awt.FlowLayout());

        pnlHome.setAlignmentX(0.0F);
        pnlHome.setAlignmentY(0.0F);
        pnlHome.setPreferredSize(new java.awt.Dimension(1024, 768));
        pnlHome.setLayout(null);

        pnlHeader.setPreferredSize(new java.awt.Dimension(1024, 150));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/info/images/Backgroundheader.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.setAlignmentY(0.0F);
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel4.setMaximumSize(new java.awt.Dimension(1022, 148));
        jLabel4.setMinimumSize(new java.awt.Dimension(1022, 148));
        jLabel4.setPreferredSize(new java.awt.Dimension(1022, 148));

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlHome.add(pnlHeader);
        pnlHeader.setBounds(0, 0, 1033, 148);

        pnlBread.setBackground(new java.awt.Color(255, 255, 255));
        pnlBread.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        pnlBread.setAlignmentX(0.0F);
        pnlBread.setAlignmentY(0.0F);
        pnlBread.setPreferredSize(new java.awt.Dimension(1022, 440));
        pnlBread.setLayout(null);

        layerdPaneLogIn.setLayout(new java.awt.CardLayout());

        pnlLogIn.setBackground(new java.awt.Color(255, 255, 255));
        pnlLogIn.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(44, 95, 125))); // NOI18N
        pnlLogIn.setPreferredSize(new java.awt.Dimension(400, 300));
        pnlLogIn.setLayout(null);

        lblUserName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblUserName.setText("Username (ORU-account):");
        pnlLogIn.add(lblUserName);
        lblUserName.setBounds(15, 65, 150, 15);

        txtUserName.setColumns(10);
        txtUserName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        pnlLogIn.add(txtUserName);
        txtUserName.setBounds(170, 60, 114, 25);

        lblUserPassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblUserPassword.setText("Password");
        pnlLogIn.add(lblUserPassword);
        lblUserPassword.setBounds(15, 114, 51, 15);

        pwdUserPassword.setColumns(10);
        pwdUserPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        pwdUserPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdUserPasswordActionPerformed(evt);
            }
        });
        pwdUserPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pwdUserPasswordKeyPressed(evt);
            }
        });
        pnlLogIn.add(pwdUserPassword);
        pwdUserPassword.setBounds(170, 110, 114, 25);

        btnLogIn.setBackground(new java.awt.Color(44, 95, 125));
        btnLogIn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnLogIn.setForeground(new java.awt.Color(255, 255, 255));
        btnLogIn.setText("Log in");
        btnLogIn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInActionPerformed(evt);
            }
        });
        pnlLogIn.add(btnLogIn);
        btnLogIn.setBounds(170, 160, 120, 37);

        layerdPaneLogIn.add(pnlLogIn, "card9");

        pnlBread.add(layerdPaneLogIn);
        layerdPaneLogIn.setBounds(325, 22, 400, 300);

        pnlHome.add(pnlBread);
        pnlBread.setBounds(0, 156, 1022, 440);

        pnlFooter.setToolTipText("");
        pnlFooter.setMinimumSize(new java.awt.Dimension(1022, 148));
        pnlFooter.setPreferredSize(new java.awt.Dimension(1022, 148));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/info/images/Backgroundfooter.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setAlignmentY(0.0F);
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel3.setMaximumSize(new java.awt.Dimension(1022, 148));
        jLabel3.setMinimumSize(new java.awt.Dimension(1022, 148));
        jLabel3.setPreferredSize(new java.awt.Dimension(1022, 148));

        javax.swing.GroupLayout pnlFooterLayout = new javax.swing.GroupLayout(pnlFooter);
        pnlFooter.setLayout(pnlFooterLayout);
        pnlFooterLayout.setHorizontalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFooterLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlFooterLayout.setVerticalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlHome.add(pnlFooter);
        pnlFooter.setBounds(0, 600, 1022, 148);

        getContentPane().add(pnlHome);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logIn() {
        String userID = txtUserName.getText();
        char[] password = pwdUserPassword.getPassword();
        StringBuilder sb = new StringBuilder("");
        String convertedPassword = sb.append(password).toString();
        if (Validation.checkTextFieldEmpty(txtUserName) && Validation.checkPassword(pwdUserPassword)) {
            try {
                ArrayList<String> allusers = db.getDB().fetchColumn("select USER_ID from USER");
                if (allusers.contains(userID)) {
                    String storedPassword = db.getDB().fetchSingle("select PASSWORD from USER where USER_ID = '" + userID + "'");
                    // String name = db.getDB().fetchSingle("select NAME from USER_PROFILE where PROFILE_ID = '" + userID + "'");
                    //  ArrayList<String> userGroup = db.getDB().fetchColumn("select RESEARCH_GROUP from GROUP_MEMBERS where MEMBER = '" + userID + "'");

                    if (storedPassword.equals(convertedPassword)) {
                        new User(userID);
                        JOptionPane.showMessageDialog(null, "Welcome " + User.getName() + ". You have successfully logged in.");
                        new Home().setVisible(true);
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(null, "Wrong password, please try again.");
                        pwdUserPassword.requestFocusInWindow();
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Wrong username, please try again.");
                    txtUserName.requestFocusInWindow();
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "An error occurred");
            }
        }
    }

    private void btnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInActionPerformed
        logIn();
    }//GEN-LAST:event_btnLogInActionPerformed

    private void pwdUserPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdUserPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdUserPasswordActionPerformed

    private void pwdUserPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwdUserPasswordKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            logIn();
        }
    }//GEN-LAST:event_pwdUserPasswordKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogIn;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane layerdPaneLogIn;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lblUserPassword;
    private javax.swing.JPanel pnlBread;
    private javax.swing.JPanel pnlFooter;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlLogIn;
    private javax.swing.JPasswordField pwdUserPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables

}
