/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package info;

/**
 *
 * @author fabia
 */
public class SeeBooking extends javax.swing.JFrame {

    /**
     * Creates new form SeeBooking
     */
    public SeeBooking() {
        initComponents();
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackgroundSeeBooking = new javax.swing.JPanel();
        pnlBookingCalender = new javax.swing.JPanel();
        pnlSortSeeBooking = new javax.swing.JPanel();
        rbtnSortByDate = new javax.swing.JRadioButton();
        rbtnSortByLocation = new javax.swing.JRadioButton();
        rbtnSortByUser = new javax.swing.JRadioButton();
        pnlMyMeetings = new javax.swing.JPanel();
        spnMyMeeting = new javax.swing.JScrollPane();
        tblMyMeeting = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.FlowLayout());

        pnlBackgroundSeeBooking.setBackground(new java.awt.Color(126, 197, 239));
        pnlBackgroundSeeBooking.setPreferredSize(new java.awt.Dimension(998, 550));

        javax.swing.GroupLayout pnlBookingCalenderLayout = new javax.swing.GroupLayout(pnlBookingCalender);
        pnlBookingCalender.setLayout(pnlBookingCalenderLayout);
        pnlBookingCalenderLayout.setHorizontalGroup(
            pnlBookingCalenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 219, Short.MAX_VALUE)
        );
        pnlBookingCalenderLayout.setVerticalGroup(
            pnlBookingCalenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 169, Short.MAX_VALUE)
        );

        pnlSortSeeBooking.setBackground(new java.awt.Color(44, 95, 125));
        pnlSortSeeBooking.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        rbtnSortByDate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbtnSortByDate.setForeground(new java.awt.Color(255, 255, 255));
        rbtnSortByDate.setText("Date");
        rbtnSortByDate.setContentAreaFilled(false);

        rbtnSortByLocation.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbtnSortByLocation.setForeground(new java.awt.Color(255, 255, 255));
        rbtnSortByLocation.setText("Location");
        rbtnSortByLocation.setContentAreaFilled(false);

        rbtnSortByUser.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbtnSortByUser.setForeground(new java.awt.Color(255, 255, 255));
        rbtnSortByUser.setText("User");
        rbtnSortByUser.setContentAreaFilled(false);

        javax.swing.GroupLayout pnlSortSeeBookingLayout = new javax.swing.GroupLayout(pnlSortSeeBooking);
        pnlSortSeeBooking.setLayout(pnlSortSeeBookingLayout);
        pnlSortSeeBookingLayout.setHorizontalGroup(
            pnlSortSeeBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSortSeeBookingLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSortSeeBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtnSortByUser)
                    .addComponent(rbtnSortByDate)
                    .addComponent(rbtnSortByLocation))
                .addGap(40, 40, 40))
        );
        pnlSortSeeBookingLayout.setVerticalGroup(
            pnlSortSeeBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSortSeeBookingLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(rbtnSortByUser)
                .addGap(18, 18, 18)
                .addComponent(rbtnSortByDate)
                .addGap(18, 18, 18)
                .addComponent(rbtnSortByLocation)
                .addContainerGap())
        );

        pnlMyMeetings.setBackground(new java.awt.Color(44, 95, 125));
        pnlMyMeetings.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        spnMyMeeting.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        tblMyMeeting.setBackground(new java.awt.Color(153, 204, 255));
        tblMyMeeting.setForeground(new java.awt.Color(51, 51, 51));
        tblMyMeeting.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title", "Date", "Location", "Time", "Action"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblMyMeeting.setGridColor(new java.awt.Color(255, 255, 255));
        spnMyMeeting.setViewportView(tblMyMeeting);

        javax.swing.GroupLayout pnlMyMeetingsLayout = new javax.swing.GroupLayout(pnlMyMeetings);
        pnlMyMeetings.setLayout(pnlMyMeetingsLayout);
        pnlMyMeetingsLayout.setHorizontalGroup(
            pnlMyMeetingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMyMeetingsLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(spnMyMeeting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        pnlMyMeetingsLayout.setVerticalGroup(
            pnlMyMeetingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMyMeetingsLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(spnMyMeeting, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlBackgroundSeeBookingLayout = new javax.swing.GroupLayout(pnlBackgroundSeeBooking);
        pnlBackgroundSeeBooking.setLayout(pnlBackgroundSeeBookingLayout);
        pnlBackgroundSeeBookingLayout.setHorizontalGroup(
            pnlBackgroundSeeBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundSeeBookingLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(pnlBackgroundSeeBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlBookingCalender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlSortSeeBooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(pnlMyMeetings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );
        pnlBackgroundSeeBookingLayout.setVerticalGroup(
            pnlBackgroundSeeBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundSeeBookingLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pnlBackgroundSeeBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlMyMeetings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlBackgroundSeeBookingLayout.createSequentialGroup()
                        .addComponent(pnlBookingCalender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlSortSeeBooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 137, Short.MAX_VALUE))
        );

        getContentPane().add(pnlBackgroundSeeBooking);

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlBackgroundSeeBooking;
    private javax.swing.JPanel pnlBookingCalender;
    private javax.swing.JPanel pnlMyMeetings;
    private javax.swing.JPanel pnlSortSeeBooking;
    private javax.swing.JRadioButton rbtnSortByDate;
    private javax.swing.JRadioButton rbtnSortByLocation;
    private javax.swing.JRadioButton rbtnSortByUser;
    private javax.swing.JScrollPane spnMyMeeting;
    private javax.swing.JTable tblMyMeeting;
    // End of variables declaration//GEN-END:variables
}
