/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package info;

/**
 *
 * @author fabia
 */
public class SeeYourPost extends javax.swing.JFrame {

    /** Creates new form SeeYourPost */
    public SeeYourPost() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackgroundSeeYourPost = new javax.swing.JPanel();
        spnMyResearchPost = new javax.swing.JScrollPane();
        tblMyResearchPost = new javax.swing.JTable();
        spnMyEducationPost = new javax.swing.JScrollPane();
        tblMyEducationPost = new javax.swing.JTable();
        spnMyGeneralPost = new javax.swing.JScrollPane();
        tblMyGeneralPost = new javax.swing.JTable();
        pnlHeaderGeneral = new javax.swing.JPanel();
        lblSeePostGeneral = new javax.swing.JLabel();
        pnlHeaderEducation = new javax.swing.JPanel();
        lblSeePostEducation = new javax.swing.JLabel();
        pnlHeaderResearch = new javax.swing.JPanel();
        lblSeePostResearch = new javax.swing.JLabel();
        pnlBackgroundSortMyPost = new javax.swing.JPanel();
        rbtnSortByMyResearchPost = new javax.swing.JRadioButton();
        rbtnSortByMyEducationPost = new javax.swing.JRadioButton();
        rbtnSortByMyGeneralPost = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.FlowLayout());

        pnlBackgroundSeeYourPost.setBackground(new java.awt.Color(126, 197, 239));
        pnlBackgroundSeeYourPost.setPreferredSize(new java.awt.Dimension(998, 613));

        spnMyResearchPost.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        tblMyResearchPost.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Post_ID", "Title", "Description", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblMyResearchPost.setGridColor(new java.awt.Color(255, 255, 255));
        tblMyResearchPost.setShowGrid(false);
        spnMyResearchPost.setViewportView(tblMyResearchPost);

        spnMyEducationPost.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        tblMyEducationPost.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Post_ID", "Title", "Description", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblMyEducationPost.setGridColor(new java.awt.Color(255, 255, 255));
        spnMyEducationPost.setViewportView(tblMyEducationPost);

        spnMyGeneralPost.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        tblMyGeneralPost.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Post_ID", "Title", "Description", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblMyGeneralPost.setGridColor(new java.awt.Color(255, 255, 255));
        spnMyGeneralPost.setViewportView(tblMyGeneralPost);

        pnlHeaderGeneral.setBackground(new java.awt.Color(44, 95, 125));
        pnlHeaderGeneral.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lblSeePostGeneral.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSeePostGeneral.setForeground(new java.awt.Color(255, 255, 255));
        lblSeePostGeneral.setText("General");

        javax.swing.GroupLayout pnlHeaderGeneralLayout = new javax.swing.GroupLayout(pnlHeaderGeneral);
        pnlHeaderGeneral.setLayout(pnlHeaderGeneralLayout);
        pnlHeaderGeneralLayout.setHorizontalGroup(
            pnlHeaderGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSeePostGeneral)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlHeaderGeneralLayout.setVerticalGroup(
            pnlHeaderGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSeePostGeneral)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlHeaderEducation.setBackground(new java.awt.Color(44, 95, 125));
        pnlHeaderEducation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lblSeePostEducation.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSeePostEducation.setForeground(new java.awt.Color(255, 255, 255));
        lblSeePostEducation.setText("Education");

        javax.swing.GroupLayout pnlHeaderEducationLayout = new javax.swing.GroupLayout(pnlHeaderEducation);
        pnlHeaderEducation.setLayout(pnlHeaderEducationLayout);
        pnlHeaderEducationLayout.setHorizontalGroup(
            pnlHeaderEducationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderEducationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSeePostEducation)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlHeaderEducationLayout.setVerticalGroup(
            pnlHeaderEducationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderEducationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSeePostEducation)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlHeaderResearch.setBackground(new java.awt.Color(44, 95, 125));
        pnlHeaderResearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lblSeePostResearch.setBackground(new java.awt.Color(44, 95, 125));
        lblSeePostResearch.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSeePostResearch.setForeground(new java.awt.Color(255, 255, 255));
        lblSeePostResearch.setText("Research");

        javax.swing.GroupLayout pnlHeaderResearchLayout = new javax.swing.GroupLayout(pnlHeaderResearch);
        pnlHeaderResearch.setLayout(pnlHeaderResearchLayout);
        pnlHeaderResearchLayout.setHorizontalGroup(
            pnlHeaderResearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderResearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSeePostResearch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlHeaderResearchLayout.setVerticalGroup(
            pnlHeaderResearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderResearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSeePostResearch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlBackgroundSortMyPost.setBackground(new java.awt.Color(44, 95, 125));
        pnlBackgroundSortMyPost.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        rbtnSortByMyResearchPost.setBackground(new java.awt.Color(44, 95, 125));
        rbtnSortByMyResearchPost.setForeground(new java.awt.Color(255, 255, 255));
        rbtnSortByMyResearchPost.setText("Research");

        rbtnSortByMyEducationPost.setBackground(new java.awt.Color(44, 95, 125));
        rbtnSortByMyEducationPost.setForeground(new java.awt.Color(255, 255, 255));
        rbtnSortByMyEducationPost.setText("Education");

        rbtnSortByMyGeneralPost.setBackground(new java.awt.Color(44, 95, 125));
        rbtnSortByMyGeneralPost.setForeground(new java.awt.Color(255, 255, 255));
        rbtnSortByMyGeneralPost.setText("General");

        javax.swing.GroupLayout pnlBackgroundSortMyPostLayout = new javax.swing.GroupLayout(pnlBackgroundSortMyPost);
        pnlBackgroundSortMyPost.setLayout(pnlBackgroundSortMyPostLayout);
        pnlBackgroundSortMyPostLayout.setHorizontalGroup(
            pnlBackgroundSortMyPostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundSortMyPostLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBackgroundSortMyPostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtnSortByMyResearchPost)
                    .addComponent(rbtnSortByMyGeneralPost)
                    .addComponent(rbtnSortByMyEducationPost))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBackgroundSortMyPostLayout.setVerticalGroup(
            pnlBackgroundSortMyPostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundSortMyPostLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtnSortByMyEducationPost)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnSortByMyGeneralPost)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnSortByMyResearchPost)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlBackgroundSeeYourPostLayout = new javax.swing.GroupLayout(pnlBackgroundSeeYourPost);
        pnlBackgroundSeeYourPost.setLayout(pnlBackgroundSeeYourPostLayout);
        pnlBackgroundSeeYourPostLayout.setHorizontalGroup(
            pnlBackgroundSeeYourPostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundSeeYourPostLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(pnlBackgroundSortMyPost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(pnlBackgroundSeeYourPostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(spnMyResearchPost, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
                    .addComponent(pnlHeaderResearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spnMyEducationPost)
                    .addComponent(pnlHeaderGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spnMyGeneralPost)
                    .addComponent(pnlHeaderEducation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        pnlBackgroundSeeYourPostLayout.setVerticalGroup(
            pnlBackgroundSeeYourPostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundSeeYourPostLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlBackgroundSeeYourPostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBackgroundSeeYourPostLayout.createSequentialGroup()
                        .addComponent(pnlBackgroundSortMyPost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlBackgroundSeeYourPostLayout.createSequentialGroup()
                        .addComponent(pnlHeaderResearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(spnMyResearchPost, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(pnlHeaderEducation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnMyEducationPost, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(pnlHeaderGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnMyGeneralPost, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
        );

        getContentPane().add(pnlBackgroundSeeYourPost);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblSeePostEducation;
    private javax.swing.JLabel lblSeePostGeneral;
    private javax.swing.JLabel lblSeePostResearch;
    private javax.swing.JPanel pnlBackgroundSeeYourPost;
    private javax.swing.JPanel pnlBackgroundSortMyPost;
    private javax.swing.JPanel pnlHeaderEducation;
    private javax.swing.JPanel pnlHeaderGeneral;
    private javax.swing.JPanel pnlHeaderResearch;
    private javax.swing.JRadioButton rbtnSortByMyEducationPost;
    private javax.swing.JRadioButton rbtnSortByMyGeneralPost;
    private javax.swing.JRadioButton rbtnSortByMyResearchPost;
    private javax.swing.JScrollPane spnMyEducationPost;
    private javax.swing.JScrollPane spnMyGeneralPost;
    private javax.swing.JScrollPane spnMyResearchPost;
    private javax.swing.JTable tblMyEducationPost;
    private javax.swing.JTable tblMyGeneralPost;
    private javax.swing.JTable tblMyResearchPost;
    // End of variables declaration//GEN-END:variables

}
